### ISSUE TITLE
UK Society of Genealogists

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-research-links#63] opened 2022-08-17 21:09 UTC
The [Society of Genealogists](https://www.sog.org.uk) has an extensive database of digitized sources.  They only show the sources to members, but the search is public and lists which sources a name was found in.

Thinking that such a list might help find another way to access the source (or give a link to someone who is a member), I prepared a plugin that can do the search.  
[SocietyofGenealogistsPlugin.php.zip](https://github.com/JustCarmen/webtrees-fancy-research-links/files/9366072/SocietyofGenealogistsPlugin.php.zip)

Two things it can't do, because I'm not sure how: (1) narrow down the place; and (2) allow the user to select variations on search that are menu controlled.

**Comment by JustCarmen** [comment] 2022-08-25 19:44
I added an option to use the country in plugins. See: https://github.com/JustCarmen/webtrees-fancy-research-links/commit/69f9163f4426ba98cadcf48027397c11a9ccc75a. Use $attributes['COUNTRY'] in your plugin to get the desired result.

But I am not sure where the country comes in in your plugin SocietyofGenealogistsPlugin so would you please update the plugin before I add it to the module? Thanks.

For your information: I did update the Familysearch plugin. See #64.

**Comment by WGroleau** [comment] 2022-08-25 20:24
On Aug 25, 2022, at 12:44, Carmen ***@***.***> wrote:
> I added an option to use the country in plugins. See: 69f9163. Use $attributes['COUNTRY'] in your plugin to get the desired result.
> 
> But I am not sure where the country comes in in your plugin SocietyofGenealogistsPlugin so would you please update the plugin before I add it to the module? Thanks.
> 
> For your information: I did update the Familysearch plugin. See #64.

I don’t know how to fix the SoG plugin.  Their “place” field does not say birth or death, and it expects a _county_ in UK.

-- 
Wes Groleau
伟思礼

"We should be careful to get out of an experience only the wisdom that is in it—and stop there; lest we be like the cat that sits down on a hot stove-lid.  She will never sit down on a hot stove-lid again—and that is well, also, she will not sit down on a cold one any more, and that limitation is unnecessary.”
        — Mark Twain

**Comment by WGroleau** [comment] 2022-08-25 20:45
Comparing the files I have with the differences on GitHub, it looks like I have
the right code.

But I got "Undefined array key "BIRT" …/modules_v4/jc-fancy-research-links/plugins/FamilySearchPlugin.php:33

Changed it to “BIRTH” which seemed to be in the main module code, but got the same error.

And then I see a comment that birth is deprecated and will be removed.  ??

-- 
Wes Groleau

无论是黑猫还是白猫，能捉到老鼠的就是好猫。
——邓小平
Doesn’t matter if the cat is black or white, as long as it catches mice.
——Deng Xiaoping

**Comment by JustCarmen** [comment] 2022-08-26 12:37
> But I got "Undefined array key "BIRT" …/modules_v4/jc-fancy-research-links/plugins/FamilySearchPlugin.php:33

The deprecated variable you mention is not used in the latest development version of the FamilySearch plugin. But you shouldn't get an error. Unfortunately, I can't reproduce the error. I suspect it is caused by a mixture of old and new files. Could that be the case? Make sure that you are using the latest development version of both the file FancyResearchLinksModule and the FamilySearchPlugin.

> I don’t know how to fix the SoG plugin.  Their “place” field does not say birth or death, and it expects a _county_ in UK.

I thought you were looking for a way to add the country in the search form of the SoG plugin.  I cannot add an option for county, because it is not possible to extract the county from the full place name. We can't determine what position of the full place name the county is in. If there is one.

**Comment by WGroleau** [comment] 2022-08-26 15:50
On Aug 26, 2022, at 05:37, Carmen ***@***.***> wrote:
> The deprecated variable you mention is not used in the latest development version of the FamilySearch plugin. But you shouldn't get an error. Unfortunately, I can't reproduce the error. I suspect it is caused by a mixture of old and new files. Could that be the case? Make sure that you are using the latest development version of both the file FancyResearchLinksModule and the FamilySearchPlugin.

I thought there must be a mixture, though I couldn’t figure out how it may have happened.  So I made a local git directory and did a pull of everything.  I copied all of it into my webtrees site (even the git housekeeping files) and I still got the error.  Puzzled.  Now my server seems to be down, including the provider’s domain name.  So any more troubleshooting will have to wait.

> I thought you were looking for a way to add the country in the search form of the SoG plugin. I cannot add an option for county, because it is not possible to extract the county from the full place name. We can't determine what position of the full place name the county is in. If there is one.

That’s what I figured.  I just left that field blank so the user can decide what to fill in when the SoG page comes up.  It’s not very useful without a paid subscription, though it does give a list of sources to look in, if one can find those elsewhere.

An idea: an optional setting for a brief help text.  If empty, prints nothing, but if filled in, next to the name of the plugin would be a help icon which on hover (or on click) pops up the text the plugin creator has entered.

--  
Wes Groleau
伟思礼

“If you are offered a free lunch, you are the lunch”

**Comment by JustCarmen** [comment] 2022-09-01 06:39
I've added the plugin to the plugin folder.

> An idea: an optional setting for a brief help text.  If empty, prints nothing, but if filled in, next to the name of the plugin would be a help icon which on hover (or on click) pops up the text the plugin creator has entered.

I don't know. It will make the list a bit messy I guess. I have to think about it.

**Comment by Shemwell** [comment] 2022-09-03 18:37
In the 1.7 version I was able to get the State (2nd position from end) in the FamilySearch plugin by using:
 
if ($name['birthplace']) {
// $birthplace is the full placename e.g. "Palos Heights, Cook County, Illinois, USA"
  $birthplace = ' ' . $name['birthplace'];
if (empty($birthplace)) {
   $shortbirthplace = '';
}
else if (!isset(array_reverse(explode(", ", $birthplace))[1])) {
     $shortbirthplace = $birthplace;
	 }else	{
$shortbirthplace = '' . array_reverse(explode(", ", $birthplace))[1];
		}
but this does not work with the newer versions.

Is there any way to reverse the place location to get the State or just get the 2nd place location from the end?

**Comment by JustCarmen** [comment] 2022-09-13 12:34
I have simplified the attributes to choose by using only the city/town in the search results. In most cases, this is sufficient. Recently I added the country to the attributes. So it is possible to use the first part of the full place name (city) or the last part of the full place name (country). All other parts are not used in normal circumstances because the position of those parts in the full place name is different. We cannot determine the position of the state or district because it depends on the country. You state that the 2nd position from the end is the state name. This is correct for place names in the US, but does not count for many other places in the world. So your search plugin gives correct results only if the person was born in the US.

That said you can add this to your plugin:

```
$request = app(ServerRequestInterface::class);
assert($request instanceof ServerRequestInterface);

$tree       = Validator::attributes($request)->tree();
$xref       = Validator::attributes($request)->isXref()->string('xref', '');
$individual = Registry::individualFactory()->make($xref, $tree);

$eplaces = $individual->getAllEventPlaces(['BIRT']);

$birthplace = '';
if ($eplaces !== []) {
    foreach($eplaces as $eplace) {
        $fullplacename[] = strip_tags($eplace->fullName());
    }
    $birthplace = $fullplacename[0];
}
```
$birthplace contains the full place name (string).

Don't forget to call the used classes at the top of the file:

```
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Validator;
use Psr\Http\Message\ServerRequestInterface;
```

**Comment by WGroleau** [comment] 2022-09-13 15:53
On Sep 13, 2022, at 05:34, Carmen ***@***.***> wrote:
> I have simplified the attributes to choose by using only the city/town in the search results. In most cases, this is sufficient. Recently I added the country to the attributes. So it is possible to use the first part of the full place name (city) or the last part of the full place name (country). All other parts are not used in normal circumstances because the position of those parts in the full place name is different. We cannot determine the position of the state or district because it depends on the country. You state that the 2nd position from the end is the state name. This is correct for place names in the US, but does not count for many other places in the world. So your search plugin gives correct results only if the person was born in the US.

I can’t speak for anyone else, but for me, the "2nd position from the end is the state name” is only true for USA and Canada.  The equivalents elsewhere (department in France, voivoidship in Poland, comunidad in Spain, district, region, etc. are rather inconsistent.  The other parts are even inconsistent in north America because sometimes the state/province is the smallest I can find, sometimes the county, sometimes the township, …

But the UK SOG (as far as I know) only has UK data, so what’s in USA doesn’t matter.  That’s why I did not bother to try to include the location in that plugin.

-- 
Wes Groleau
伟思礼

  I have discovered in my 60+ years of ministry
  that I have won more to Christ by just being present
  when they need someone to display the love of God.
  I didn't have to preach or quote a scripture.
  Somehow God takes over from there.
            J. R. Farley

**Comment by JustCarmen** [comment] 2022-09-14 04:07
> I can’t speak for anyone else, but for me, the "2nd position from the end is the state name” is only true for USA and Canada.  The equivalents elsewhere (department in France, voivoidship in Poland, comunidad in Spain, district, region, etc. are rather inconsistent.  The other parts are even inconsistent in north America because sometimes the state/province is the smallest I can find, sometimes the county, sometimes the township, …

I think we are both saying the same thing. Namely, that the state's position in the place hierarchy is inconsistent or unavailable.

To be clear: I was responding to @Shemwell (https://github.com/JustCarmen/webtrees-fancy-research-links/issues/63#issuecomment-1236179428)

**Comment by JustCarmen** [comment] 2022-09-14 04:13
See: https://github.com/JustCarmen/webtrees-fancy-research-links/issues/63#issuecomment-1233812957

> An idea: an optional setting for a brief help text. If empty, prints nothing, but if filled in, next to the name of the plugin would be a help icon which on hover (or on click) pops up the text the plugin creator has entered.

I've decided to not implement such a feature. Most links speaks for themselves and in most cases the forms on the research websites are clear enough to know what to add or change to get results. I want to keep the list in the sidebar as simple as possible.

**Comment by JustCarmen** [comment] 2022-09-14 04:14
I am closing this issue now that the original question has been answered and the SOG plugin has been added to the module.

**Closed by JustCarmen** 2022-09-14 04:14 UTC
